package io.flutter.plugins

import androidx.annotation.Keep
import com.baseflow.permissionhandler.PermissionHandlerPlugin
import io.flutter.Log
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.pathprovider.PathProviderPlugin
import vn.hunghd.flutterdownloader.FlutterDownloaderPlugin
/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
object GeneratedPluginRegistrant {
    private const val TAG = "GeneratedPluginRegistrant"
    fun registerWith(flutterEngine: FlutterEngine) {
        try {
            flutterEngine.plugins.add(FlutterDownloaderPlugin())
        } catch (e: Exception) {
            Log.e(
                TAG,
                "Error registering plugin flutter_downloader, vn.hunghd.flutterdownloader.FlutterDownloaderPlugin",
                e
            )
        }

        try {
            flutterEngine.plugins.add(PathProviderPlugin())
        } catch (e: Exception) {
            Log.e(
                TAG,
                "Error registering plugin path_provider_android, io.flutter.plugins.pathprovider.PathProviderPlugin",
                e
            )
        }
        try {
            flutterEngine.plugins.add(PermissionHandlerPlugin())
        } catch (e: Exception) {
            Log.e(
                TAG,
                "Error registering plugin permission_handler, com.baseflow.permissionhandler.PermissionHandlerPlugin",
                e
            )
        }
    }
}